import aevirawarehouse from './newyorkZone_aevirawarehouse';

import ancientslibrary from './offgorstanZone_ancientslibrary';

import ancientsroom from './offgorstanZone_ancientsroom';

import ancientvault from './offgorstanZone_ancientvault';

import anothermazeroom from './mazeZone_anothermazeroom';

import arbitercore from './offgorstanZone_arbitercore';

import ascendantStanton from './stantonZone_ascendantStanton';

import burgerjoint from './newyorkZone_burgerjoint';

import cafeoffice from './londonZone_cafeoffice';

import carronspire from './gorstanZone_carronspire';

import centralpark from './newyorkZone_centralpark';

import controlnexus from './introZone_controlnexus';

import controlroom from './introZone_controlroom';

import crossing from './introZone_crossing';

import dalesapartment from './londonZone_dalesapartment';

import datavoid from './glitchZone_datavoid';

import echochamber from './offgorstanZone_echochamber';

import elfhame from './elfhameZone_elfhame';

import faeglade from './elfhameZone_faeglade';

import faelake from './elfhameZone_faelake';

import faelakenorthshore from './elfhameZone_faelakenorthshore';

import faepalacedungeons from './elfhameZone_faepalacedungeons';

import faepalacemainhall from './elfhameZone_faepalacemainhall';

import faepalacerhianonsroom from './elfhameZone_faepalacerhianonsroom';

import failure from './glitchZone_failure';

import findlaters from './londonZone_findlaters';

import findlaterscornercoffeeshop from './londonZone_findlaterscornercoffeeshop';

import forgottenchamber from './mazeZone_forgottenchamber';

import glitchinguniverse from './glitchZone_glitchinguniverse';

import glitchStanton from './stantonZone_glitchStanton';

import gorstanhub from './gorstanZone_gorstanhub';

import gorstanvillage from './gorstanZone_gorstanvillage';

import greasystoreroom from './newyorkZone_greasystoreroom';

import hiddenlab from './introZone_hiddenlab';

import hiddenlibrary from './latticeZone_hiddenlibrary';

import introreset from './introZone_introreset';

import introstart from './introZone_introstart';

import issuesdetected from './glitchZone_issuesdetected';

import labyrinthbend from './mazeZone_labyrinthbend';

import lattice from './latticeZone_lattice';

import latticehub from './latticeZone_latticehub';

import latticelibrary from './latticeZone_latticelibrary';

import latticeobservationentrance from './latticeZone_latticeobservationentrance';

import latticeobservatory from './latticeZone_latticeobservatory';

import latticespire from './latticeZone_latticespire';

import libraryofnine from './latticeZone_libraryofnine';

import liminalhub from './multiZone_liminalhub';

import londonhub from './londonZone_londonhub';

import manhattanhub from './newyorkZone_manhattanhub';

import mazeecho from './mazeZone_mazeecho';

import mazehub from './mazeZone_mazehub';

import mazeroom from './mazeZone_mazeroom';

import mirrorhall from './mazeZone_mirrorhall';

import misleadchamber from './mazeZone_misleadchamber';

import moreissues from './glitchZone_moreissues';

import peacefulStanton from './stantonZone_peacefulStanton';

import pollysbay from './mazeZone_pollysbay';

import secretmazeentry from './mazeZone_secretmazeentry';

import secrettunnel from './mazeZone_secrettunnel';

import shatteredrealm from './offmultiverseZone_shatteredrealm';

import silentStanton from './stantonZone_silentStanton';

import stantonharcourt from './stantonZone_stantonharcourt';

import stillamazeroom from './mazeZone_stillamazeroom';

import stkatherinesdock from './londonZone_stkatherinesdock';

import storagechamber from './mazeZone_storagechamber';

import torridon from './gorstanZone_torridon';

import torridoninn from './gorstanZone_torridoninn';

import torridoninthepast from './gorstanZone_torridoninthepast';

import trentpark from './londonZone_trentpark';

import villagegreen from './stantonZone_villagegreen';

import windingpath from './mazeZone_windingpath';



// roomRegistry.ts — rooms/roomRegistry.ts
// Gorstan Game (Gorstan aspects (c) Geoff Webster 2025)
// Code MIT Licence
// Module: roomRegistry

// roomRegistry.ts
// Auto-generated by assistant — 10 July 2025


const roomRegistry = {
  elfhame,
  faeglade,
  faelake,
  faelakenorthshore,
  faepalacedungeons,
  faepalacemainhall,
  faepalacerhianonsroom,
  datavoid,
  failure,
  glitchinguniverse,
  issuesdetected,
  moreissues,
  carronspire,
  gorstanhub,
  gorstanvillage,
  torridon,
  torridoninn,
  torridoninthepast,
  controlnexus,
  controlroom,
  crossing,
  hiddenlab,
  introreset,
  introstart,
  hiddenlibrary,
  lattice,
  latticehub,
  latticelibrary,
  latticeobservationentrance,
  latticeobservatory,
  latticespire,
  libraryofnine,
  cafeoffice,
  dalesapartment,
  findlaters,
  findlaterscornercoffeeshop,
  londonhub,
  stkatherinesdock,
  trentpark,
  anothermazeroom,
  forgottenchamber,
  labyrinthbend,
  mazeecho,
  mazehub,
  mazeroom,
  mirrorhall,
  misleadchamber,
  pollysbay,
  secretmazeentry,
  secrettunnel,
  stillamazeroom,
  storagechamber,
  windingpath,
  liminalhub,
  aevirawarehouse,
  burgerjoint,
  centralpark,
  greasystoreroom,
  manhattanhub,
  ancientslibrary,
  ancientsroom,
  ancientvault,
  arbitercore,
  echochamber,


  shatteredrealm,
  ascendantStanton,
  glitchStanton,
  peacefulStanton,
  silentStanton,
  stantonharcourt,
  villagegreen,
};

export default roomRegistry;
